id: IE9A71B9B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T23:41:18+00:00'
last_modified: '2022-06-09T04:46:54.297388+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23774
  title: 'གསུང་འབུམ། འཇིགས་མེད་ཕུན་ཚོགས་འབྱུང་གནས། ༼གསེར་རྟ་བླ་རུང་དགོན་གྱི་པར་མ༽

    '
  volume:
    a3322aae47474d0fa637ef2b36cd3234:
      image_group_id: I3007
      title: ''
      volume_number: 1
      total_pages: 350
    a0bde3dc369145c0947ca3e2c23c0f6b:
      image_group_id: I3008
      title: ''
      volume_number: 2
      total_pages: 610
    ae1f2582bd9e46eabb95f70927d50f4c:
      image_group_id: I3009
      title: ''
      volume_number: 3
      total_pages: 588
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FB9D:
      image_group_id: I3007
      title: ''
      total_pages: 350
      order: 1
      base_file: FB9D.txt
    '5424':
      image_group_id: I3008
      title: ''
      total_pages: 610
      order: 2
      base_file: 5424.txt
    '9909':
      image_group_id: I3009
      title: ''
      total_pages: 588
      order: 3
      base_file: 9909.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
